spring:
  application:
    name: api-gateway

#api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#striping api/v1 in path , this is only part of api gateway url -> and further URL
  #pattern will be taken care by
        #respective servers
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Vishal
            #we can pass many info to the down stream req
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
